stages:
- name: Build
  steps:
  - runScriptConfig:
      image: golang:1.11
      shellScript: |-
        mkdir -p /go
        ln -s `pwd` /go/pipeline-example-go
        cd /go/pipeline-example-go
        go build -o bin/hello-server
        go test -cover
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloserver:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34276
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
notification: {}
